# Generated by Django 4.1 on 2022-12-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "honours",
                    models.BooleanField(
                        default=True, verbose_name="Suitable for Honours"
                    ),
                ),
                (
                    "mds",
                    models.BooleanField(default=True, verbose_name="Suitable for MDS"),
                ),
                (
                    "engineering",
                    models.BooleanField(verbose_name="Suitable for Engineering"),
                ),
                (
                    "primary",
                    models.CharField(max_length=50, verbose_name="Primary Supervisor"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Primary Supervisor Email"
                    ),
                ),
                (
                    "cosupervisors",
                    models.TextField(
                        blank=True, verbose_name="Co-supervisors/Sponsors"
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="Research Link")),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Date Created"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="Last Modified"),
                ),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
    ]
