# Generated by Django 4.1 on 2022-12-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=30, verbose_name="First name"),
                ),
                ("lastname", models.CharField(max_length=30, verbose_name="Last name")),
                (
                    "department",
                    models.CharField(
                        max_length=50, verbose_name="Department or School"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("web", models.URLField(blank=True, verbose_name="Web link")),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="external",
            field=models.TextField(
                blank=True, verbose_name="External supervisors/mentors/sponsors"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cosupervisors",
            field=models.TextField(blank=True, verbose_name="Co-supervisors"),
        ),
        migrations.AlterField(
            model_name="project",
            name="primary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.supervisor"
            ),
        ),
    ]
