# Generated by Django 4.1 on 2022-12-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_supervisor_project_external_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="primary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.supervisor",
            ),
        ),
    ]
