# Generated by Django 4.1 on 2022-12-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_email_project_current_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="short",
            field=models.TextField(blank=True, verbose_name="Short description"),
        ),
    ]
