# Generated by Django 4.1 on 2022-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_supervisor_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="numstudents",
            field=models.CharField(blank=True, max_length=30, verbose_name="Students"),
        ),
    ]
