# Generated by Django 4.1.5 on 2023-01-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_other_project_se_alter_project_engineering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, max_length=60, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='project',
            name='engineering',
            field=models.BooleanField(default=False, verbose_name='Suitable for General Engineering'),
        ),
    ]
