# Generated by Django 4.1.5 on 2023-01-24 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_skills_alter_project_engineering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='primary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.supervisor'),
        ),
    ]
