# Generated by Django 4.1.5 on 2023-02-02 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cosupervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.supervisor', verbose_name='Co-Supervisor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external',
            field=models.TextField(blank=True, verbose_name='External Supervisors/Mentors/Sponsors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other',
            field=models.CharField(blank=True, max_length=40, verbose_name='Other (please specify)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='projects.supervisor', verbose_name='Primary Supervisor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='references',
            field=models.TextField(blank=True, verbose_name='Sample References'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Topic Title'),
        ),
    ]
