# Generated by Django 4.1.5 on 2023-02-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_cosupervisor_alter_project_external_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='cosupervisors',
        ),
        migrations.AlterField(
            model_name='project',
            name='other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other (please specify)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, max_length=200, verbose_name='Skills'),
        ),
    ]
